"""Demo Telegram bot commands and workflows for Bot Builder."""

DEMO_COMMANDS = [
    {
        "key": "start",
        "command": "/start",
        "title": "Start",
        "description": "Welcome, auto-create account, show packages to buy",
        "response_text": "Welcome! Pick a package with /buy or the Buy button below.",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 10,
    },
    {
        "key": "help",
        "command": "/help",
        "title": "Help",
        "description": "Commands list plus upload formats for all scrapers (same as /formats)",
        "response_text": (
            "Use /formats for upload rules, /scrapers for sources, /run source=… to start. "
            "Full guide: TELEGRAM_USERS.md"
        ),
        "enabled": True,
        "audience": "everyone",
        "sort_order": 20,
    },
    {
        "key": "formats",
        "command": "/formats",
        "title": "File formats",
        "description": "Upload rules for all scrapers (Maps, Search/dorks, emails, Facebook, social)",
        "response_text": "",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 25,
    },
    {
        "key": "scrapers",
        "command": "/scrapers",
        "title": "Scrapers",
        "description": "List allowed scraper modules + /run source= examples",
        "response_text": "",
        "enabled": True,
        "audience": "users",
        "sort_order": 28,
    },
    {
        "key": "whoami",
        "command": "/whoami",
        "title": "Who am I",
        "description": "Show your Telegram id and link status",
        "response_text": "",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 30,
    },
    {
        "key": "packages",
        "command": "/packages",
        "title": "Packages",
        "description": "Alias of /buy — list packages (upgrade-only while subscribed)",
        "response_text": "",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 40,
    },
    {
        "key": "buy",
        "command": "/buy",
        "title": "Buy / Upgrade",
        "description": "Order a package (guests: all plans; subscribed: higher tier only). Menu shows Upgrade when subscribed.",
        "response_text": "",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 50,
    },
    {
        "key": "upgrade",
        "command": "/upgrade",
        "title": "Upgrade",
        "description": "Alias of /buy — higher-tier packages only while subscribed",
        "response_text": "",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 51,
    },
    {
        "key": "paid",
        "command": "/paid",
        "title": "Paid (USDT TxID)",
        "description": "Submit TRC-20 or BEP-20 TxID (≥20 confirmations for auto-grant)",
        "response_text": "Usage: /paid <txid>",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 60,
    },
    {
        "key": "subscription",
        "command": "/subscription",
        "title": "Subscription",
        "description": "Show your current plan",
        "response_text": "",
        "enabled": True,
        "audience": "users",
        "sort_order": 70,
    },
    {
        "key": "run",
        "command": "/run",
        "title": "Run job",
        "description": "Queue a scrape after uploading inputs (source= / use_dork= / threads=…)",
        "response_text": (
            "Usage: /run [source=gmaps|google_search|tiktok_shop|email_harvest|"
            "email_validate|youtube|…] [name=MyJob] [engine=chrome] [threads=2] "
            "[use_dork=yes] [validate_after=yes] [max_results=50]\n"
            "Upload keywords (+ locations unless email_validate or Google dorks). "
            "See /scrapers and /formats. Guide: TELEGRAM_USERS.md"
        ),
        "enabled": True,
        "audience": "subscribers",
        "sort_order": 80,
    },
    {
        "key": "status",
        "command": "/status",
        "title": "Job status",
        "description": "Running jobs, progress %, and recent stats (menu: Status)",
        "response_text": "",
        "enabled": True,
        "audience": "users",
        "sort_order": 90,
    },
    {
        "key": "jobs",
        "command": "/jobs",
        "title": "My jobs",
        "description": "Alias for /status — same progress view (not a menu button)",
        "response_text": "",
        "enabled": True,
        "audience": "users",
        "sort_order": 91,
    },
    {
        "key": "stats",
        "command": "/stats",
        "title": "Job stats",
        "description": "Alias for /status — progress % and row counts",
        "response_text": "",
        "enabled": True,
        "audience": "users",
        "sort_order": 92,
    },
    {
        "key": "stop",
        "command": "/stop",
        "title": "Stop",
        "description": "Stop your own queued or running job",
        "response_text": "",
        "enabled": True,
        "audience": "subscribers",
        "sort_order": 100,
    },
    {
        "key": "support",
        "command": "/support",
        "title": "Support",
        "description": "Open or follow up on a support ticket",
        "response_text": "Send /support followed by your message.",
        "enabled": True,
        "audience": "users",
        "sort_order": 110,
    },
    # --- Telegram admin (role=admin + admin_commands_enabled) ---
    {
        "key": "admin",
        "command": "/admin",
        "title": "Admin menu",
        "description": "Telegram admin command menu + reply keyboard",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 190,
    },
    {
        "key": "users",
        "command": "/users",
        "title": "List users",
        "description": "/users [page] — list panel users",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 200,
    },
    {
        "key": "userinfo",
        "command": "/userinfo",
        "title": "User info",
        "description": "/userinfo <tg|id|username>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 201,
    },
    {
        "key": "adduser",
        "command": "/adduser",
        "title": "Add Telegram user",
        "description": "/adduser <telegram_id> [name] [package_slug] [days]",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 202,
    },
    {
        "key": "setname",
        "command": "/setname",
        "title": "Rename user",
        "description": "/setname <key> <new_username>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 203,
    },
    {
        "key": "settg",
        "command": "/settg",
        "title": "Set Telegram id",
        "description": "/settg <key> <telegram_id|none>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 204,
    },
    {
        "key": "setperm",
        "command": "/setperm",
        "title": "Set user perm",
        "description": "/setperm <key> <perm>=<value>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 205,
    },
    {
        "key": "deluser",
        "command": "/deluser",
        "title": "Delete user",
        "description": "/deluser <key> confirm",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 206,
    },
    {
        "key": "disable",
        "command": "/disable",
        "title": "Disable user",
        "description": "/disable <telegram_id|username>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 210,
    },
    {
        "key": "enable",
        "command": "/enable",
        "title": "Enable user",
        "description": "/enable <telegram_id|username>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 211,
    },
    {
        "key": "subs",
        "command": "/subs",
        "title": "Active subscriptions",
        "description": "/subs [page]",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 220,
    },
    {
        "key": "grant",
        "command": "/grant",
        "title": "Grant subscription",
        "description": "/grant <telegram_id|username> <package_slug> [days]",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 221,
    },
    {
        "key": "revoke",
        "command": "/revoke",
        "title": "Revoke subscription",
        "description": "/revoke <telegram_id|username>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 222,
    },
    {
        "key": "extend",
        "command": "/extend",
        "title": "Extend subscription",
        "description": "/extend <telegram_id|username> <days>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 223,
    },
    {
        "key": "pending",
        "command": "/pending",
        "title": "Pending orders",
        "description": "List pending manual payments",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 230,
    },
    {
        "key": "approve",
        "command": "/approve",
        "title": "Approve payment",
        "description": "Approve pending order: /approve <order_id>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 231,
    },
    {
        "key": "reject",
        "command": "/reject",
        "title": "Reject payment",
        "description": "/reject <order_id> [reason]",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 232,
    },
    {
        "key": "workers",
        "command": "/workers",
        "title": "List workers",
        "description": "/workers [page] — online status, drain, leases",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 240,
    },
    {
        "key": "servers",
        "command": "/servers",
        "title": "Servers",
        "description": "Alias for /workers",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 241,
    },
    {
        "key": "worker",
        "command": "/worker",
        "title": "Worker details",
        "description": "/worker <id|name>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 242,
    },
    {
        "key": "addworker",
        "command": "/addworker",
        "title": "Create worker",
        "description": "/addworker <name> [max_browsers] — token shown once (DM if group)",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 243,
    },
    {
        "key": "editworker",
        "command": "/editworker",
        "title": "Edit worker",
        "description": "/editworker <id|name> name=… max_browsers=…",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 244,
    },
    {
        "key": "workerdrain",
        "command": "/workerdrain",
        "title": "Drain worker",
        "description": "/workerdrain <id|name> [on|off]",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 245,
    },
    {
        "key": "workeron",
        "command": "/workeron",
        "title": "Enable worker",
        "description": "/workeron <id|name>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 246,
    },
    {
        "key": "workeroff",
        "command": "/workeroff",
        "title": "Disable worker",
        "description": "/workeroff <id|name>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 247,
    },
    {
        "key": "workertoken",
        "command": "/workertoken",
        "title": "Rotate worker token",
        "description": "/workertoken <id|name> — token DM’d privately",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 248,
    },
    {
        "key": "adminpkgs",
        "command": "/adminpkgs",
        "title": "Admin packages",
        "description": "List all packages including disabled",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 250,
    },
    {
        "key": "addpkg",
        "command": "/addpkg",
        "title": "Create package",
        "description": "/addpkg <slug> <name> <price> <days> [threads] [upload]",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 251,
    },
    {
        "key": "editpkg",
        "command": "/editpkg",
        "title": "Edit package",
        "description": "/editpkg <slug> key=value…",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 252,
    },
    {
        "key": "disablepkg",
        "command": "/disablepkg",
        "title": "Disable package",
        "description": "/disablepkg <slug>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 253,
    },
    {
        "key": "alljobs",
        "command": "/alljobs",
        "title": "All jobs",
        "description": "/alljobs [page] — any user's jobs",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 260,
    },
    {
        "key": "job",
        "command": "/job",
        "title": "Job details",
        "description": "/job <public_id>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 261,
    },
    {
        "key": "adminstop",
        "command": "/adminstop",
        "title": "Stop any job",
        "description": "/adminstop <public_id>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 262,
    },
    {
        "key": "proxies",
        "command": "/proxies",
        "title": "Proxy pools",
        "description": "List proxy pools + toggle",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 270,
    },
    {
        "key": "proxy",
        "command": "/proxy",
        "title": "Toggle proxy pool",
        "description": "/proxy <id> on|off",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 271,
    },
    {
        "key": "captcha",
        "command": "/captcha",
        "title": "Captcha status",
        "description": "/captcha [off] — status / disable solvers (keys in panel)",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 280,
    },
    {
        "key": "tickets",
        "command": "/tickets",
        "title": "Support tickets",
        "description": "/tickets [open|closed|all] [page]",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 281,
    },
    {
        "key": "ticket",
        "command": "/ticket",
        "title": "View ticket",
        "description": "/ticket <id> — show thread",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 282,
    },
    {
        "key": "reply",
        "command": "/reply",
        "title": "Reply to ticket",
        "description": "/reply <id> <message> — user notified on Telegram",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 283,
    },
    {
        "key": "close",
        "command": "/close",
        "title": "Close ticket",
        "description": "/close <id> [reason] — user notified",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 284,
    },
    {
        "key": "botstatus",
        "command": "/botstatus",
        "title": "Bot status",
        "description": "Bot enabled / admin_commands flags (no token)",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 290,
    },
    {
        "key": "boton",
        "command": "/boton",
        "title": "Enable bot",
        "description": "Set BotSettings.enabled=true",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 291,
    },
    {
        "key": "botoff",
        "command": "/botoff",
        "title": "Disable bot",
        "description": "Set BotSettings.enabled=false (pauses polling)",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 292,
    },
]

DEMO_WORKFLOWS = [
    {
        "key": "onboarding",
        "name": "Onboarding",
        "description": "Guide new Telegram users: auto-account → packages → buy → ready",
        "enabled": True,
        "is_demo": True,
        "sort_order": 10,
        "definition": {
            "trigger": "command:/start",
            "steps": [
                {"action": "ensure_telegram_user"},
                {"if": "no_subscription", "say": "Welcome. Use Buy on the menu or tap a package below."},
                {"if": "subscribed", "say": "You are ready. Upload .txt/.csv (caption keywords/locations/emails), then /run source=…. See /scrapers and /formats."},
            ],
        },
    },
    {
        "key": "buy_usdt",
        "name": "Buy with USDT (TRC-20 / BEP-20)",
        "description": "packages → pick package (higher tier only if subscribed) → pick network → QR + /paid (≥20 confirmations auto-grant)",
        "enabled": True,
        "is_demo": True,
        "sort_order": 20,
        "definition": {
            "trigger": "command:/buy",
            "steps": [
                {"action": "show_packages_inline"},
                {"wait": "callback:buy:<slug>"},
                {"action": "show_network_inline"},
                {"wait": "callback:buynet:<slug>:<trc20|bep20>"},
                {"action": "create_order"},
                {"action": "send_payment_details_and_qr"},
                {"wait": "command:/paid"},
                {"action": "verify_onchain_min_20_confirmations"},
                {"action": "activate_subscription"},
                {"action": "refresh_reply_keyboard"},
                {"action": "notify_user"},
            ],
        },
    },
    {
        "key": "buy_manual",
        "name": "Buy with manual payment",
        "description": "Bank/other details → admin approve in panel or /approve",
        "enabled": True,
        "is_demo": True,
        "sort_order": 30,
        "definition": {
            "trigger": "command:/buy",
            "steps": [
                {"action": "create_order"},
                {"action": "send_manual_instructions"},
                {"wait": "admin_approve"},
                {"action": "activate_subscription"},
                {"action": "notify_user"},
            ],
        },
    },
    {
        "key": "job_run",
        "name": "Job run & delivery",
        "description": "Upload inputs → /run source=… (any enabled scraper) → progress → ZIP via Telegram + panel",
        "enabled": True,
        "is_demo": True,
        "sort_order": 40,
        "definition": {
            "trigger": "command:/run",
            "steps": [
                {"action": "validate_subscription_and_perms"},
                {"action": "validate_input_files"},
                {"action": "create_job"},
                {"action": "dispatch_to_workers"},
                {"action": "notify_progress"},
                {"action": "merge_and_zip"},
                {"action": "deliver_telegram_and_panel"},
            ],
        },
    },
    {
        "key": "job_progress",
        "name": "Job progress & stats",
        "description": "User sees running jobs, progress %, done/total searches, and rows saved via Status (/status; aliases /jobs /stats)",
        "enabled": True,
        "is_demo": True,
        "sort_order": 45,
        "definition": {
            "trigger": "command:/status",
            "steps": [
                {"action": "list_own_active_jobs"},
                {"say": "Show progress % and searches done/total for each running job"},
                {"action": "list_recent_job_stats"},
                {"say": "Include rows saved, engine, and status for recent jobs"},
            ],
        },
    },
    {
        "key": "job_stop",
        "name": "Stop with partial results",
        "description": "/stop → cancel → merge partial → send ZIP",
        "enabled": True,
        "is_demo": True,
        "sort_order": 50,
        "definition": {
            "trigger": "command:/stop",
            "steps": [
                {"action": "cancel_own_job"},
                {"action": "merge_partial"},
                {"action": "deliver_results"},
            ],
        },
    },
    {
        "key": "expiry_reminder",
        "name": "Subscription expiry reminder",
        "description": "Cron: remind before expiry; block /run when expired",
        "enabled": True,
        "is_demo": True,
        "sort_order": 60,
        "definition": {
            "trigger": "cron:daily",
            "steps": [
                {"action": "find_expiring_soon"},
                {"action": "telegram_remind"},
                {"action": "mark_expired_block_run"},
            ],
        },
    },
    {
        "key": "support_ticket",
        "name": "Support via Telegram",
        "description": "/support → ticket → support chat; admin /reply|/close or panel → user notified",
        "enabled": True,
        "is_demo": True,
        "sort_order": 70,
        "definition": {
            "trigger": "command:/support",
            "steps": [
                {"if": "support_disabled", "say": "Support is not configured."},
                {"action": "create_or_append_ticket"},
                {"action": "forward_to_support_chat"},
                {"say": "Ticket created/updated. Admins reply via Telegram (/reply) or Admin → Support; you get replies here instantly."},
            ],
        },
    },
    {
        "key": "worker_down",
        "name": "Worker offline alert",
        "description": "Admin alert when a worker misses heartbeats",
        "enabled": True,
        "is_demo": True,
        "sort_order": 80,
        "definition": {
            "trigger": "event:worker_offline",
            "steps": [
                {"action": "notify_admins_telegram"},
            ],
        },
    },
    {
        "key": "payment_failed",
        "name": "Payment verification failed",
        "description": "Invalid/replay TxID → user message + rate limit",
        "enabled": True,
        "is_demo": True,
        "sort_order": 90,
        "definition": {
            "trigger": "event:payment_failed",
            "steps": [
                {"action": "rate_limit_paid"},
                {"say": "Payment not verified. Check TxID and try again later if rate-limited."},
            ],
        },
    },
    {
        "key": "telegram_admin",
        "name": "Telegram admin control plane",
        "description": "Linked role=admin + admin_commands_enabled → /admin CRUD for users, subs, workers, jobs",
        "enabled": True,
        "is_demo": True,
        "sort_order": 100,
        "definition": {
            "trigger": "command:/admin",
            "steps": [
                {"if": "not_admin_or_flag_off", "say": "Admins only (enable admin commands in Bot Builder)."},
                {"action": "show_admin_menu_keyboard"},
                {"say": "Users/subs/workers/packages/jobs/proxies/captcha/bot via slash commands; secrets stay in panel."},
            ],
        },
    },
]
