"""Demo Telegram bot commands and workflows for Bot Builder."""

DEMO_COMMANDS = [
    {
        "key": "start",
        "command": "/start",
        "title": "Start",
        "description": "Welcome and onboarding entry",
        "response_text": "Welcome! Use /help to see available commands.",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 10,
    },
    {
        "key": "help",
        "command": "/help",
        "title": "Help",
        "description": "Dynamic help based on enabled features",
        "response_text": "Commands are listed dynamically from Bot Builder.",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 20,
    },
    {
        "key": "whoami",
        "command": "/whoami",
        "title": "Who am I",
        "description": "Show your Telegram id and link status",
        "response_text": "",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 30,
    },
    {
        "key": "packages",
        "command": "/packages",
        "title": "Packages",
        "description": "List subscription packages",
        "response_text": "",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 40,
    },
    {
        "key": "buy",
        "command": "/buy",
        "title": "Buy",
        "description": "Order a subscription package",
        "response_text": "Usage: /buy <package_slug>",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 50,
    },
    {
        "key": "paid",
        "command": "/paid",
        "title": "Paid (USDT)",
        "description": "Submit TRC-20 transaction id for verification",
        "response_text": "Usage: /paid <txid>",
        "enabled": True,
        "audience": "everyone",
        "sort_order": 60,
    },
    {
        "key": "subscription",
        "command": "/subscription",
        "title": "Subscription",
        "description": "Show your current plan",
        "response_text": "",
        "enabled": True,
        "audience": "users",
        "sort_order": 70,
    },
    {
        "key": "run",
        "command": "/run",
        "title": "Run job",
        "description": "Start a scrape job with your uploaded inputs",
        "response_text": "Usage: /run [engine=chrome] [threads=2]",
        "enabled": True,
        "audience": "subscribers",
        "sort_order": 80,
    },
    {
        "key": "status",
        "command": "/status",
        "title": "Status",
        "description": "Live progress for YOUR jobs only",
        "response_text": "",
        "enabled": True,
        "audience": "users",
        "sort_order": 90,
    },
    {
        "key": "stop",
        "command": "/stop",
        "title": "Stop",
        "description": "Stop your running job",
        "response_text": "",
        "enabled": True,
        "audience": "subscribers",
        "sort_order": 100,
    },
    {
        "key": "support",
        "command": "/support",
        "title": "Support",
        "description": "Open a support ticket via Telegram",
        "response_text": "Send /support followed by your message.",
        "enabled": True,
        "audience": "users",
        "sort_order": 110,
    },
    {
        "key": "servers",
        "command": "/servers",
        "title": "Servers",
        "description": "List workers (admin Telegram)",
        "response_text": "",
        "enabled": False,
        "audience": "admins",
        "sort_order": 200,
    },
    {
        "key": "pending",
        "command": "/pending",
        "title": "Pending orders",
        "description": "List pending manual payments",
        "response_text": "",
        "enabled": False,
        "audience": "admins",
        "sort_order": 210,
    },
    {
        "key": "approve",
        "command": "/approve",
        "title": "Approve payment",
        "description": "Approve pending order: /approve <order_id>",
        "response_text": "",
        "enabled": False,
        "audience": "admins",
        "sort_order": 220,
    },
    {
        "key": "grant",
        "command": "/grant",
        "title": "Grant subscription",
        "description": "/grant <telegram_id|username> <package_slug> [days]",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 230,
    },
    {
        "key": "revoke",
        "command": "/revoke",
        "title": "Revoke subscription",
        "description": "/revoke <telegram_id|username>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 240,
    },
    {
        "key": "extend",
        "command": "/extend",
        "title": "Extend subscription",
        "description": "/extend <telegram_id|username> <days>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 250,
    },
    {
        "key": "disable",
        "command": "/disable",
        "title": "Disable user",
        "description": "/disable <telegram_id|username>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 260,
    },
    {
        "key": "enable",
        "command": "/enable",
        "title": "Enable user",
        "description": "/enable <telegram_id|username>",
        "response_text": "",
        "enabled": True,
        "audience": "admins",
        "sort_order": 270,
    },
]

DEMO_WORKFLOWS = [
    {
        "key": "onboarding",
        "name": "Onboarding",
        "description": "Guide new Telegram users: account link → subscription → ready",
        "enabled": True,
        "is_demo": True,
"sort_order": 10,
        "definition": {
            "trigger": "command:/start",
            "steps": [
                {"if": "user_missing", "say": "No panel account linked. Ask an admin to create your user and set your Telegram ID."},
                {"if": "no_subscription", "say": "No active subscription. Send /packages to buy access."},
                {"if": "subscribed", "say": "You are ready. Upload keywords & locations, then /run."},
            ],
        },
    },
    {
        "key": "buy_usdt",
        "name": "Buy with USDT (TRC-20)",
        "description": "/buy → payment instructions → /paid → on-chain verify → activate",
        "enabled": True,
        "is_demo": True,
"sort_order": 20,
        "definition": {
            "trigger": "command:/buy",
            "steps": [
                {"action": "create_order"},
                {"action": "send_usdt_instructions"},
                {"wait": "command:/paid"},
                {"action": "verify_trc20"},
                {"action": "activate_subscription"},
                {"action": "notify_user"},
            ],
        },
    },
    {
        "key": "buy_manual",
        "name": "Buy with manual payment",
        "description": "Bank/other details → admin approve in panel or /approve",
        "enabled": True,
        "is_demo": True,
"sort_order": 30,
        "definition": {
            "trigger": "command:/buy",
            "steps": [
                {"action": "create_order"},
                {"action": "send_manual_instructions"},
                {"wait": "admin_approve"},
                {"action": "activate_subscription"},
                {"action": "notify_user"},
            ],
        },
    },
    {
        "key": "job_run",
        "name": "Job run & delivery",
        "description": "Upload inputs → /run → progress → ZIP via Telegram + panel",
        "enabled": True,
        "is_demo": True,
"sort_order": 40,
        "definition": {
            "trigger": "command:/run",
            "steps": [
                {"action": "validate_subscription_and_perms"},
                {"action": "create_job"},
                {"action": "dispatch_to_workers"},
                {"action": "notify_progress"},
                {"action": "merge_and_zip"},
                {"action": "deliver_telegram_and_panel"},
            ],
        },
    },
    {
        "key": "job_stop",
        "name": "Stop with partial results",
        "description": "/stop → cancel → merge partial → send ZIP",
        "enabled": True,
        "is_demo": True,
"sort_order": 50,
        "definition": {
            "trigger": "command:/stop",
            "steps": [
                {"action": "cancel_own_job"},
                {"action": "merge_partial"},
                {"action": "deliver_results"},
            ],
        },
    },
    {
        "key": "expiry_reminder",
        "name": "Subscription expiry reminder",
        "description": "Cron: remind before expiry; block /run when expired",
        "enabled": True,
        "is_demo": True,
"sort_order": 60,
        "definition": {
            "trigger": "cron:daily",
            "steps": [
                {"action": "find_expiring_soon"},
                {"action": "telegram_remind"},
                {"action": "mark_expired_block_run"},
            ],
        },
    },
    {
        "key": "support_ticket",
        "name": "Support via Telegram",
        "description": "/support → ticket → configured support chat",
        "enabled": True,
        "is_demo": True,
"sort_order": 70,
        "definition": {
            "trigger": "command:/support",
            "steps": [
                {"if": "support_disabled", "say": "Support is not configured."},
                {"action": "create_ticket"},
                {"action": "forward_to_support_chat"},
                {"say": "Ticket created. An admin will reply here if configured."},
            ],
        },
    },
    {
        "key": "worker_down",
        "name": "Worker offline alert",
        "description": "Admin alert when a worker misses heartbeats",
        "enabled": True,
        "is_demo": True,
"sort_order": 80,
        "definition": {
            "trigger": "event:worker_offline",
            "steps": [
                {"action": "notify_admins_telegram"},
            ],
        },
    },
    {
        "key": "payment_failed",
        "name": "Payment verification failed",
        "description": "Invalid/replay TxID → user message + rate limit",
        "enabled": True,
        "is_demo": True,
"sort_order": 90,
        "definition": {
            "trigger": "event:payment_failed",
            "steps": [
                {"action": "rate_limit_paid"},
                {"say": "Payment not verified. Check TxID and try again later if rate-limited."},
            ],
        },
    },
]
